-- SISTEMA DE CRIAÇÃO
CREATE TABLE IF NOT EXISTS sist_cria (
    id SERIAL PRIMARY KEY,
    sigla VARCHAR(10) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);

-- NÍVEL TERRITORIAL
CREATE TABLE IF NOT EXISTS niv_terr (
    id SERIAL PRIMARY KEY,
    nivel VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);

-- CÓDIGO TERRITORIAL
CREATE TABLE IF NOT EXISTS cod_terr (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);

-- NOME TERRITORIAL
CREATE TABLE IF NOT EXISTS nom_terr (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);

-- CLASSE DE GALINÁCEOS
CREATE TABLE IF NOT EXISTS cl_gal (
    id SERIAL PRIMARY KEY,
    sigla VARCHAR(10) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);
